services:
  slack_order:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1000}
    restart: always
    environment:
      USER_ID: ${USER_ID}
      SLACK_APP_TOKEN: ${SLACK_APP_TOKEN}
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
    volumes:
      - ./slack_order.py:/app/slack_order.py
